#Site settings
title: Golden Reach
email: goldenreachorg@gmail.com
url:  https://kietcannguyen.github.io/GoldenReach.github.io/
description: "Non-proft connecting with our seniors!"
keywords: "golden reach, golden, reach"
skills: "Youth-led non-profit organization dedicated to connecting with the senior community!"
meta_author: Nguyen Kiet & Shek Truman

#Google webmaster tools
google_verify:

#https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

#Contact form:
#static : pass through formspree.io to validate email sending
#disqus : replace contact form by disqus thread
#comment the line below if you want to stick with the default PHP contact form
contact: static

#If you use disqus you need disqus shortname
#https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

#Color settings (hex-codes without the leading hash-tag)
color:
  primary: e1bf6f
  primary-rgb: "225,191,111"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

#Footer settings
footer:
  copyright: Dr. Henry Jekyll
  location: Location
  social: Around the Web
  credits: Credits

#Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:

  - title: tiktok
    url: https://www.tiktok.com/@goldenreachorg?_t=8jafJD7LVkY&_r=1
  - title: instagram
    url: https://www.instagram.com/goldenreachorg/


#Postal address (add as many lines as necessary)
address:
  - line: Houston, Texas

#Credits content
credits: 'Megan Nguyen & Kytlyn Bui'


#Build settings
markdown: kramdown
permalink: pretty

#for post
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
